### ISSUE TITLE
can't seem to compile head 

### ISSUE THREAD

**Issue by mcfiredrill** [savonet/liquidsoap#425]
(truncated)
```
OCAMLOPT -c ogg_formats/ogg_flac_encoder.ml
OCAMLOPT -c io/udp_io.ml
OCAMLOPT -c io/oss_io.ml
OCAMLOPT -c analyze/analyze_rms.ml
OCAMLOPT -c playlists/playlist_basic.ml
OCAMLOPT -c visualization/vumeter.ml
OCAMLOPT -c visualization/midimeter.ml
OCAMLOPT -c visualization/video_volume.ml
OCAMLOPT -c visualization/vis_volume.ml
OCAMLOPT -c synth/keyboard.ml
OCAMLOPT -c synth/synth_op.ml
OCAMLOPT -c decoder/metadata_decoder.ml
OCAMLOPT -c decoder/wav_aiff_decoder.ml
OCAMLOPT -c decoder/midi_decoder.ml
OCAMLOPT -c decoder/image_decoder.ml
OCAMLOPT -c decoder/image/ppm_decoder.ml
OCAMLOPT -c decoder/external_decoder.ml
OCAMLOPT -c decoder/raw_audio_decoder.ml
OCAMLOPT -c decoder/flac_decoder.ml
OCAMLOPT -c decoder/aac_decoder.ml
OCAMLOPT -c decoder/ogg_decoder.ml
OCAMLOPT -c decoder/mad_decoder.ml
OCAMLOPT -c decoder/vorbisduration.ml
OCAMLOPT -c decoder/flacduration.ml
OCAMLOPT -c decoder/ogg_flac_duration.ml
OCAMLOPT -c decoder/taglib_plug.ml
OCAMLOPT -c shebang.ml
OCAMLOPT -c lang/lang_builtins.ml
File "lang/lang_builtins.ml", line 103, characters 17-40:
Error: Unbound value String.capitalize_ascii
make[3]: *** [lang/lang_builtins.cmx] Error 2
make[3]: Leaving directory `/home/liquidsoap/liquidsoap-full/liquidsoap/src'
make[2]: *** [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory `/home/liquidsoap/liquidsoap-full/liquidsoap/src'
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory `/home/liquidsoap/liquidsoap-full/liquidsoap'
make: *** [all] Error 1
The command '/bin/bash -c cd /home/liquidsoap/liquidsoap-full; eval `opam config env`; make;' returned a non-zero code: 2
```

**Comment by toots** [comment]
Hi @mcfiredrill! This should be fixed in the latest `master` branch.

**Comment by mcfiredrill** [comment]
thanks!

**Comment by flashl** [comment]
Greetings. Forgive me if a new issue should be created rather than commenting in this thread. I found this thread while googling compile error produced from OCAMLOPT -c lang/lang_builtins.ml.  After reading this thread I tried git: checkout/rebase/pull origin master/merge to ensure I had latest master. The Builtins-ml error persists although previous git commands reports "Current branch master is up to date."   

I'm using instructions here: http://savonet.sourceforge.net/download.html#latest. Please advise what I'm overlooking.

Thanks in advance.

**Comment by flashl** [comment]
Seems invariably each time after writing a post for help, I manage to stumble upon an answer. For me, builtins.ml complaint disappeared after re-running 1) make init; 2) make update; and 3) ./bootstrap.
